title: bolty.net
description: motorcycles, yay!

url: http://bolty.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html
 - title: SV650
   url: /sv650

social:
   twitter: boltynet
   email: stacy@bolty.net

google_analytics: "UA-58263416-1xxx"
