title: bolty.net
description: motorcycles and stuff

url: http://bolty.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: SV650
   url: /sv650

social:
   rss: http://feeds.feedburner.com/bolty/feed
   twitter: boltynet
   email: stacy@bolty.net

google_analytics: "UA-4912070-2"

defaults:
  -
    scope:
      path: "_drafts"
      type: "posts"
    values:
      comments: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
