title: Devour Miles
description: motorcycles and stuff

url: http://devourmiles.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: SV650
   url: /sv650
 - title: Travels
   url: /blog/tag/travels

social:
   rss: http://feeds.feedburner.com/bolty/feed
   twitter: boltynet
   email: stacy@devourmiles.com

google_analytics: "UA-4912070-2"

disqus_shortname: boltynet

defaults:
  -
    scope:
      path: "_drafts"
      type: "posts"
    values:
      comments: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

exclude:
  - node_modules
  - README.md
  - CNAME
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
